### ISSUE TITLE
Reproducible crash after 1250 lookups

### ISSUE THREAD

**Issue by jvoisin** [rainycape/geoip#2]
```go
package main

import (
	"fmt"
	"math/rand"
	"strconv"
	"strings"

	"github.com/rainycape/geoip"
)

func randomIPv4() string {
	blocks := []string{}
	for i := 0; i < 4; i++ {
		number := rand.Intn(255)
		blocks = append(blocks, strconv.Itoa(number))
	}
	return strings.Join(blocks, ".")
}

func main() {
	var i int64
	var ip string
	defer func() {
		if recover() != nil {
			fmt.Printf("CRASH for %v on the %dth iteration", ip, i)
		}
	}()

	db, err := geoip.Open("GeoLite2-City.mmdb")
	if err != nil {
		panic(err)
	}
	for i = 0; i < 4228250625; i++ {
		ip = randomIPv4()
		db.Lookup(ip)
	}
}
```

When run:

```
$ go run main.go
CRASH for 204.58.124.247 on the 1250th iteration
$ go run main.go
CRASH for 204.58.124.247 on the 1250th iteration
$ go run main.go
CRASH for 204.58.124.247 on the 1250th iteration
```

Without the graceful handling:

```go
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rainycape/geoip.(*decoder).decodeType(0xc42004bd48, 0x6, 0xc4a306ad80, 0x0, 0x0)
	/home/jvoisin/go/src/github.com/rainycape/geoip/decoder.go:114 +0x2e8
github.com/rainycape/geoip.(*decoder).decode(0xc42004bd48, 0x618c20, 0xc4a306ad80, 0x0, 0x0)
	/home/jvoisin/go/src/github.com/rainycape/geoip/decoder.go:142 +0x43
github.com/rainycape/geoip.(*decoder).decodeArray(0xc42004bd48, 0x223d02, 0x11e9ec9, 0x11e9ec9, 0x0, 0x0, 0x20)
	/home/jvoisin/go/src/github.com/rainycape/geoip/decoder.go:234 +0x81
github.com/rainycape/geoip.(*decoder).decode(0xc42004bd48, 0x5ddcbc, 0xc4213ce0a4, 0x504c55, 0x504c55)
	/home/jvoisin/go/src/github.com/rainycape/geoip/decoder.go:213 +0xd05
github.com/rainycape/geoip.(*GeoIP).lookupResult(0xc4218d6100, 0xf2b63c, 0xc42604a401, 0xf2b63c, 0xc42604a490, 0xe)
	/home/jvoisin/go/src/github.com/rainycape/geoip/geoip.go:181 +0x88
github.com/rainycape/geoip.(*GeoIP).lookupData(0xc4218d6100, 0xc42604a4bc, 0x4, 0x4, 0xc42604a4bc, 0x4, 0x4, 0x60, 0x10, 0x3, ...)
	/home/jvoisin/go/src/github.com/rainycape/geoip/geoip.go:131 +0x19b
github.com/rainycape/geoip.(*GeoIP).LookupIPValue(0xc4218d6100, 0xc42604a4b0, 0x10, 0x10, 0x4, 0x4, 0x65b7fb, 0x1)
	/home/jvoisin/go/src/github.com/rainycape/geoip/geoip.go:104 +0xbd
github.com/rainycape/geoip.(*GeoIP).LookupIP(0xc4218d6100, 0xc42604a4b0, 0x10, 0x10, 0x10, 0x10, 0x0)
	/home/jvoisin/go/src/github.com/rainycape/geoip/geoip.go:77 +0x4d
github.com/rainycape/geoip.(*GeoIP).Lookup(0xc4218d6100, 0xc42604a4a0, 0xe, 0xc425fe7800, 0x0, 0x0)
	/home/jvoisin/go/src/github.com/rainycape/geoip/geoip.go:71 +0x9b
main.main()
	/home/jvoisin/go/src/XXX/YYY/ZZZ/main.go:37 +0x8a
exit status 2
zsh: exit 1     go run main.go
```

**Comment by jvoisin** [comment]
Apparently, it's the `data` field that is empty (with a capacity of zero) that is the culprit, passed as parameter to the `DecodeType` method.
